// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public class ListType extends java.util.LinkedList<Type> {
    public boolean equals(Object o) {
        if (o instanceof ListType) {
            ListType casted = (ListType) o;
            if (this.size() != casted.size()) {
                throw new RuntimeException("ERROR: List types sizes differ ");
            }
            for (int i = 0; i < this.size(); i++){
                if (!this.get(i).equals(casted.get(i))) {
                    if (this.get(i) instanceof TypeTuple && !(casted.get(i) instanceof TypeTuple))
                        throw new RuntimeException("ERROR_UNEXPECTED_TUPLE");
                    return false;
                }
            }
            return true;
        }
        return false;
    }
}
