// File generated by the BNF Converter (bnfc 2.9.4.1).

package org.syntax.stella.Absyn;

public abstract class RecordFieldType implements java.io.Serializable {
  public boolean equals(Object o) {
    if (o instanceof ARecordFieldType) {
      ARecordFieldType castedO = (ARecordFieldType) o;
      ARecordFieldType castedThis = (ARecordFieldType) this;
      return (castedO.stellaident_.equals(castedThis.stellaident_) && castedThis.type_.getClass().equals(castedO.type_.getClass()));
    }
    return false;
  }
    public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(ARecordFieldType p, A arg);

  }

}
